name: Trigger auto deployment for source-java

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/source-java-AutoDeployTrigger-f34d011d-207e-448b-8b9a-ebab9f59f8b8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SOURCEJAVA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SOURCEJAVA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SOURCEJAVA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.SOURCEJAVA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SOURCEJAVA_REGISTRY_PASSWORD }}
          containerAppName: source-java
          resourceGroup: ContainerAppRG
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


